version: "3"
services:
  mongodb:
    image: mongo:4.4.26
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"